### ISSUE TITLE
sentiment_stanford on corpus?

### ISSUE THREAD

**Issue by Lucinho91** [trinker/stansent#7]
Dear Mr. Trinker,

is it also possible to use the sentiment_stanford and sentiment_stanford_by functions on a corpus? I have a corpus of about 25000 comments which I would like to perform sentiment analysis on. Right now it is running, but it is taking very long...

**Comment by trinker** [comment]
Maybe but I'm unsure.  The function was designed to work on a data.frame.  Running it on a Corpus object won't speed it up any.  The stanford tagger is slower.  In it's current form there is no way to speed it up.  You could run it in parallel but if you're newer to coding that's a bit bigger of a lift.  The **sentimentr** package may be a trade off that is faster but may be less accurate.  If it's accuracy you care about be patient with the stanford tagger.

**Comment by Lucinho91** [comment]
Dear Mr. Rinker, thank you very much for your help! Your package helped me a lot to apply the stanford tagger! Best regards from Germany!
